[package]
name = "arnolid_method"
version = "0.1.0"
authors = ["PatrickAulbach <Patrick.Aulbach@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"